### ISSUE TITLE
 "address.results[0] is undefined"

### ISSUE THREAD

**Issue by kedar2594** [reddimohan/ionic-3-google-maps-autocomplete#3]
Thanks for the code, since from past 3 months i am using methods for Google maps, 

But now i am getting issue, while dragging the marker the address will not fetch, when i checked the console. I got issue like this. 

``
error_message	You have exceeded your rate-limit for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
results	[]
status	OVER_QUERY_LIMIT

``
I searched OVER_QUERY_LIMIT issue in Google, but i didn't understood clearly,  if you faced same issue, please let me know the solution. 

Thanks in advance.

**Comment by Saqib92** [comment]
Please Create you own google map API KEY. 
From: https://console.developers.google.com/

**Comment by kedar2594** [comment]
Yeah I already created and using it since from 3 months. Now from morning, getting error like that.

**Comment by Saqib92** [comment]
As it clearly says "You have exceeded your rate-limit for this API" 
Google changed its Maps API in last 5, 6 months and decrease its limits to less request. you better purchase API according to your needs.

**Comment by kedar2594** [comment]
Oh okay, Thought it was free and now they costing for it.  Thanks for reply bro 
When the app starts, its works like charm and but after dragging the marker sometimes it will fetch correct address and after some time it will come like that. Buying it will fix this issue it seems, I will try to buy and let you know bro.

**Comment by Saqib92** [comment]
please close the issue

**Comment by kedar2594** [comment]
Sure, Thanks
