### ISSUE TITLE
i use this code in ionic 4 but so many error found

### ISSUE THREAD

**Issue by ITCODEHELP** [reddimohan/ionic-3-google-maps-autocomplete#8]
core.js:36228 Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:36228)
    at core.js:36246
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:36242)
    at new NgModuleFactory$1 (core.js:36407)
    at compileNgModuleFactory__POST_R3__ (core.js:42296)
    at PlatformRef.bootstrapModule (core.js:42663)
    at Module../src/main.ts (main.ts:11)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)

Please help me sir for convert code to ionic 4

**Comment by reddimohan** [comment]
Hi @ITCODEHELP ,

As repo name describes it is developed and tested in Ionic 3. I will try to support this for Ionic 4 when I get time.

Thanks,
MO

**Comment by ITCODEHELP** [comment]
> Hi @ITCODEHELP ,
> 
> As repo name describes it is developed and tested in Ionic 3. I will try to support this for Ionic 4 when I get time.
> 
> Thanks,
> MO

Sir, Can you give me any contact id Thank you.

**Comment by reddimohan** [comment]
Can you please give me the output of `ionic info` command

**Comment by ITCODEHELP** [comment]
> Can you please give me the output of `ionic info` command


Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (/usr/bin/node)
   npm    : 6.14.4
   OS     : Linux 5.4


  ────────────────────────────────────────────────────────────

          Ionic CLI update available: 5.4.16 → 6.10.1
                                
     The package name has changed from ionic to @ionic/cli!
                                
             To update, run: npm uninstall -g ionic
                 Then run: npm i -g @ionic/cli

**Comment by Saqib92** [comment]
@ITCODEHELP 
Check this Repo: https://github.com/Saqib92/ionic-4-Google-Maps-with-Autocomplete
it is based on this Repo.

**Comment by reddimohan** [comment]
@Saqib92 Thanks for the link, but he is looking for Ionic v5.

**Comment by Saqib92** [comment]
@reddimohan it will work on ionic 5 as well.

**Comment by ITCODEHELP** [comment]
> @reddimohan it will work on ionic 5 as well.

But sir, I get error Can't resolve any parameter and cant load page Thank you

**Comment by Saqib92** [comment]
can you share your code? ionic info and other stuff?

**Comment by ITCODEHELP** [comment]
> can you share your code? ionic info and other stuff?

not an instance of HTMLInputElement searchbar error

ion-searchbar error not get elementref work

**Comment by Saqib92** [comment]
> > can you share your code? ionic info and other stuff?
> 
> not an instance of HTMLInputElement searchbar error
> 
> ion-searchbar error not get elementref work

Just ran this Repository, Its Google API key Error. please Use VALID MAP API KEY.

**Comment by reddimohan** [comment]
> > > can you share your code? ionic info and other stuff?
> > 
> > 
> > not an instance of HTMLInputElement searchbar error
> > ion-searchbar error not get elementref work
> 
> Just ran this Repository, Its Google API key Error. please Use VALID MAP API KEY.

you have to obtain the new API key from Google and update in 2 places. read the documentation.

**Comment by emma009** [comment]
everything works fine in ionic 5, except that the search bar does not bring out addresses, can u guide? thanks for ur code

**Comment by Saqib92** [comment]
Are you Getting any Errors? secondly have you enabled Google Places API in your Google account ?

**Comment by reddimohan** [comment]
> everything works fine in ionic 5, except that the search bar does not bring out addresses, can u guide? thanks for ur code

did you get Google Map api and updated?

**Comment by emma009** [comment]
finally got it to work..using ur second tutorial..i think somethings are missing

**Comment by reddimohan** [comment]
Thanks for using my code.
Please let me know if anything is missing.

**Comment by emma009** [comment]
you commented out some part of currentlocation function...this is how i got it to work below




  async currentLocation() {

    const loading = await this.loadingController.create({
      
      duration: 130000,
      message: '<div><img src="../assets/loading.gif" class="img-align"  /> <br /></div>',
      spinner: null, 
      translucent: true,
     
      cssClass:'custom-loader-class',
      backdropDismiss: true
    });
    await loading.present();
    
    //FIRST GET THE LOCATION FROM THE DEVICE.
    this.geolocation.getCurrentPosition().then((resp) => {
      let latLng = new google.maps.LatLng(resp.coords.latitude, resp.coords.longitude);
      let mapOptions = {
        center: latLng,
        zoom: 15,
        streetViewControl: false,
        disableDefaultUI: true,
        scaleControl: true,
    zoomControl: false,
        mapTypeId: google.maps.MapTypeId.ROADMAP
        //mapTypeId: google.maps.MapTypeId.HYBRID
      } 

     this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions); 

      //let latLngObj = {'lat': resp.coords.latitude, 'long': resp.coords.longitude};

      this.map.addListener('tilesloaded', () => {
      this.map.setCenter(new google.maps.LatLng(resp.coords.latitude, resp.coords.longitude));
        this.lat = this.map.center.lat()
        this.lng = this.map.center.lng()
        console.log("KKILALALARAISRER", this.lat, this.lng);


        this.getAddress(this.lat, this.lng);

        loading.dismiss();
      }); 

  
    }).catch((error) => {
      console.log('Error getting location', error);
    });
  }
